export const STEP_IDS = {
  PROFILE_SELECTION: 'PROFILE_SELECTION',
  CANDIDATE_DETAILS: 'CANDIDATE_DETAILS',
  LOCATION: 'LOCATION',
  PARENT_DETAILS: 'PARENT_DETAILS',
  CONTACT_DETAILS: 'CONTACT_DETAILS',
  CREATE_PASSWORD: 'CREATE_PASSWORD',
  EDUCATION_CAREER: 'EDUCATION_CAREER',
  PERSONAL_DETAILS: 'PERSONAL_DETAILS',
  LIFESTYLE_INTRO: 'LIFESTYLE_INTRO',
  FAMILY_FUTURE: 'FAMILY_FUTURE',
  PARTNER_EDU_CAREER: 'PARTNER_EDU_CAREER',
  PARTNER_PHYSICAL: 'PARTNER_PHYSICAL',
  PARTNER_LIFESTYLE: 'PARTNER_LIFESTYLE'
};

export const SELF_FLOW = [
  STEP_IDS.PROFILE_SELECTION,
  STEP_IDS.CANDIDATE_DETAILS,
  STEP_IDS.LOCATION,
  STEP_IDS.CONTACT_DETAILS,
  STEP_IDS.CREATE_PASSWORD,
  STEP_IDS.EDUCATION_CAREER,
  STEP_IDS.PERSONAL_DETAILS,
  STEP_IDS.LIFESTYLE_INTRO,
  STEP_IDS.FAMILY_FUTURE,
  STEP_IDS.PARTNER_EDU_CAREER,
  STEP_IDS.PARTNER_PHYSICAL,
  STEP_IDS.PARTNER_LIFESTYLE
];

export const MANAGED_FLOW = [
  STEP_IDS.PROFILE_SELECTION,
  STEP_IDS.CANDIDATE_DETAILS,
  STEP_IDS.LOCATION,
  STEP_IDS.PARENT_DETAILS,
  STEP_IDS.CONTACT_DETAILS,
  STEP_IDS.CREATE_PASSWORD,
  STEP_IDS.EDUCATION_CAREER,
  STEP_IDS.PERSONAL_DETAILS,
  STEP_IDS.LIFESTYLE_INTRO,
  STEP_IDS.FAMILY_FUTURE,
  STEP_IDS.PARTNER_EDU_CAREER,
  STEP_IDS.PARTNER_PHYSICAL,
  STEP_IDS.PARTNER_LIFESTYLE
];

export const getActiveFlow = (profileFor) => {
  return (!profileFor || profileFor === 'myself') ? SELF_FLOW : MANAGED_FLOW;
};
