export const STEP_IDS = {
  PROFILE_SELECTION: 'PROFILE_SELECTION',
  CANDIDATE_DETAILS: 'CANDIDATE_DETAILS',
  LOCATION: 'LOCATION',
  PARENT_DETAILS: 'PARENT_DETAILS',
  CONTACT_DETAILS: 'CONTACT_DETAILS',
  CREATE_PASSWORD: 'CREATE_PASSWORD',
  EDUCATION_CAREER: 'EDUCATION_CAREER'
};

export const SELF_FLOW = [
  STEP_IDS.PROFILE_SELECTION,
  STEP_IDS.CANDIDATE_DETAILS,
  STEP_IDS.LOCATION,
  STEP_IDS.CONTACT_DETAILS,
  STEP_IDS.CREATE_PASSWORD,
  STEP_IDS.EDUCATION_CAREER
];

export const MANAGED_FLOW = [
  STEP_IDS.PROFILE_SELECTION,
  STEP_IDS.CANDIDATE_DETAILS,
  STEP_IDS.LOCATION,
  STEP_IDS.PARENT_DETAILS,
  STEP_IDS.CONTACT_DETAILS,
  STEP_IDS.CREATE_PASSWORD,
  STEP_IDS.EDUCATION_CAREER
];

export const getActiveFlow = (profileFor) => {
  return (!profileFor || profileFor === 'myself') ? SELF_FLOW : MANAGED_FLOW;
};
